### ISSUE TITLE
Preserving line breaks in event descriptions

### ISSUE THREAD

**Issue by knice** [ucsc/events-scraper#2]
I think we talked about this, but it looks like the event descriptions in Localist had their line break removed. So the description text is a single block of text. So I guess the questions are:

1. Does Localist support HTML in the description field of events when importing a CSV?
2. Or does Localist honor `\n` line breaks when importing a CSV?

If #1 is yes, can we scraped the events again and update what is in Localist with HTML descriptions?

**Comment by pguther** [comment]
Previously I had thought that Localist wouldn't allow HTML, but that was because I was trying to write the csv files myself instead of using a library so I wasn't properly escaping things.  Eventually I had to figure out how to escape stuff and now HTML works, so I can go back and rewrite part of the scraper to keep the HTML in.  I'm also considering switching to an actual python csv I/O library now to avoid further headaches down the road

**Comment by knice** [comment]
Sounds good. I'll leave this ticket open until the event descriptions are updated. If you run into any issues, leave a comment here and we'll discuss.

**Comment by pguther** [comment]
I uploaded some events to the staging site after a quick update to the scraper. 

The scraper now preserves HTML for the description, but unfortunately localist takes all the \<p> tags, combines them into one, and seperates them with \<br> tags so the spacing isn't the same.  I could come up with a fix for this though, such as adding an extra \<br> between paragraphs.

I also took the liberty of adding a custom field to the events, namely Location Details.  Before, the location details had been combined with the description, but now they have their own field along with the rest of the detail fields.  The events on the staging site have the Location Details section.  If you like the separate location details section I can leave it and we can import the rest of the events that way, if not I can change it back easily since it's just a couple lines of code that were changed for this effect.

**Comment by pguther** [comment]
Descriptions have been updated, and location details have all been moved to the custom field in the enterprise site.  I think that [this event](http://ucsc.enterprise.localist.com/event/graduate_research_symposium_7857#.WRYJio61tEI) is a good example of an event that benefits from having a location details field, just as an example

**Comment by pguther** [comment]
It also looks like the full line breaks are sometimes preserved, as seen in [this event](http://ucsc.enterprise.localist.com/event/outstanding_in_the_field_dinner_at_the_ucsc_farm#.WRYLQ461tEI)

**Comment by knice** [comment]
Since we talked and decided that this issue only matters for events we import initially, I'll close this issue.
